# Use official Node.js LTS image
FROM node:18-slim

# Set working directory
WORKDIR /app

# Copy package files first (for Docker layer caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# If you have a local Firebase service account JSON and want it included in the image,
# uncomment or provide `serviceAccountKey.json` in the build context. For secrets it's
# recommended to mount at runtime or use a secrets manager instead of baking into image.
COPY serviceAccountKey.json /app/serviceAccountKey.json
ENV FIREBASE_SERVICE_ACCOUNT_PATH=/app/serviceAccountKey.json

# Accept build-time args for secrets and config
ARG PORT
ARG DB_URL
ARG JWT_SECRET
ARG HASH_KEY
ARG CLIENT_URL
ARG BUCKET_NAME
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG NODE_ENV
ARG GMAIL_USER
ARG GMAIL_APP_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_BUCKET_NAME
ARG AWS_REGION
ARG REDIS_URL
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG TWILIO_API_KEY
ARG TWILIO_API_SECRET
ARG TWILIO_CONVERSATIONS_SERVICE_SID
ARG TWILIO_SYNC_SERVICE_SID
ARG SFTP_USERNAME
ARG SFTP_PASSWORD
ARG FIREBASE_SERVICE_ACCOUNT

# Export as environment variables for runtime
ENV PORT=$PORT \
    DB_URL=$DB_URL \
    JWT_SECRET=$JWT_SECRET \
    HASH_KEY=$HASH_KEY \
    CLIENT_URL=$CLIENT_URL \
    BUCKET_NAME=$BUCKET_NAME \
    CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
    CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
    CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
    NODE_ENV=$NODE_ENV \
    GMAIL_USER=$GMAIL_USER \
    GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
    AWS_REGION=$AWS_REGION \
    REDIS_URL=$REDIS_URL \
    TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID \
    TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN \
    TWILIO_API_KEY=$TWILIO_API_KEY \
    TWILIO_API_SECRET=$TWILIO_API_SECRET \
    TWILIO_CONVERSATIONS_SERVICE_SID=$TWILIO_CONVERSATIONS_SERVICE_SID \
    TWILIO_SYNC_SERVICE_SID=$TWILIO_SYNC_SERVICE_SID \
    SFTP_USERNAME=$SFTP_USERNAME \
    SFTP_PASSWORD=$SFTP_PASSWORD \
    FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT

# Expose the app port
EXPOSE $PORT

# Start the app
CMD ["npm", "start"]